packages:
  - .

allowBuilds:
  sharp: true
  styled-components: true
  unrs-resolver: true

blockExoticSubdeps: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # minutes (30 days)

minimumReleaseAge: 10080 # 7 days (in minutes)
