// Refreshes the drop tables from the game's own reference. One request.
//
// This is the routine refresh: the article states what every boss drops on
// every server, and those tables are what the game changes most often. It
// touches drops, item names, icon keys and the epic and subclass flags, and
// nothing else — levels and statistics are on the article too, but they belong
// to another server (see `parse-article.js`), and imagery, coordinates and
// respawn are not on it at all.
//
// Reports by default and writes only when told to, because the differences are
// worth reading before they are applied: adopting the source's spelling renames
// items, and a renamed item is a new record with a new slug.
//
// Usage:
//   pnpm --filter backend refresh:drops               report only
//   pnpm --filter backend refresh:drops:write         apply to the data files
//   pnpm --filter backend refresh:drops -- --cache=2026-09-19   read an older copy
//   pnpm --filter backend refresh:drops -- --adopt-slugs  take the source's boss slugs

const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { execFileSync } = require('node:child_process');

const { announceCopy, copyFromArgv, createSession, SERVER } = require('./fetch');
const { parseArticle } = require('./parse-article');
const { nextStep } = require('./steps');
const { replaceExport, stampSource } = require('./serialize');
const { ensureIcons, reportIcons } = require('./icons');
const { effectiveChance, toDrop } = require('./drop-row');

const ARTICLE = `/${SERVER}/posts/post/385-raid-bosses`;
const MOCKS = path.join(__dirname, '..', '..', 'mocks', 'raid-bosses');
const BOSSES_FILE = path.join(MOCKS, 'data-wiki.ts');
const DROPS_FILE = path.join(MOCKS, 'drops.ts');
const ICONS_DIR = path.join(MOCKS, 'images', 'item-icons');

/** Reads a data file the way `catalog-source.ts` does: as text, in a sandbox. */
const evaluate = (file, exported) => {
  const script = fs
    .readFileSync(file, 'utf8')
    .replace(/^import[^;]+;$/gm, '')
    .replace(/export const (\w+)\s*(?::[^=]+)?=/g, 'const $1 =')
    .concat(`\n;({ ${exported} })`);

  return vm.runInNewContext(script, Object.create(null), { timeout: 30000 });
};

const readBosses = () => evaluate(BOSSES_FILE, 'RAID_BOSSES').RAID_BOSSES;
const readDrops = () => evaluate(DROPS_FILE, 'RAID_BOSS_DROPS').RAID_BOSS_DROPS;

const DROPS_HEADER = `// What every raid boss drops, keyed by the game's own numeric id.
//
// Generated by \`pnpm --filter backend refresh:drops -- --write\`; do not edit by
// hand. Separate from \`data-wiki.ts\` because it is four fifths of the data and
// because it is refreshed by a different pass: one article request states every
// boss's drops, where everything else costs a request per boss.
//
// The chance is the rate the item actually falls at, not the weight the source
// prints. The source states drops in groups — a gate, then weights inside it
// summing to 100 — and the two are multiplied here, which is also the
// convention the catalogue started from.

import type { RaidBossDrops } from './types';

export const RAID_BOSS_DROPS: RaidBossDrops = {};
`;

/**
 * What changed, boss by boss.
 *
 * A row whose name changed but whose chance did not is reported as a rename
 * rather than as a removal and an addition, because that is what it is: the
 * source spells 78 items with an `Unidentified ` prefix the older sources
 * dropped, and calling those 207 rows "new" would hide the 287 that really are.
 */
const compare = (current, currentDrops, parsed) => {
  const report = {
    slugs: [],
    renamed: new Map(),
    added: [],
    removed: [],
    changed: [],
    regraded: [],
    iconMoved: [],
    missingIcons: new Set(),
    bosses: { only: [], gained: [] },
  };

  const byId = new Map(parsed.map((boss) => [boss.id, boss]));

  for (const boss of current) {
    const source = byId.get(boss.id);
    if (!source) {
      report.bosses.only.push(boss.name);
      continue;
    }

    // `rawChance` is kept beside the folded one for the matcher below: this
    // refresh changes the convention as well as the names, so a row can be the
    // same row under either number.
    if (source.slug !== boss.slug) report.slugs.push(`${boss.slug}  ->  ${source.slug}`);

    const rows = (source.drops.ours ?? []).map((row) => ({
      ...row,
      chance: effectiveChance(row),
      rawChance: row.chance,
    }));
    const theirs = new Map(rows.map((row) => [row.name, row]));
    const carried = currentDrops[boss.id] ?? [];
    const ours = new Map(carried.map((drop) => [drop.name, drop]));

    for (const [name, row] of theirs) {
      const drop = ours.get(name);
      if (!drop) continue;
      if (
        drop.chance !== row.chance ||
        drop.minCount !== row.minCount ||
        drop.maxCount !== row.maxCount
      ) {
        report.changed.push(`${boss.name} / ${name}: ${drop.chance}% -> ${row.chance}%`);
      }
      if (drop.itemId !== row.itemId) {
        report.iconMoved.push(`${name}: ${drop.itemId} -> ${row.itemId}`);
      }
      // A rebalance can move an item between grades, and the catalogue sorts by
      // it, so it is reported rather than applied in silence. The run that
      // first stored a grade reported all 3761 rows, the file having held none.
      const grade = (row.grade || 'ng').toLowerCase();
      if (drop.grade !== grade) {
        report.regraded.push(`${name}: ${drop.grade ?? '(none)'} -> ${grade}`);
      }
    }

    const unmatchedOurs = carried.filter((drop) => !theirs.has(drop.name));
    const unmatchedTheirs = rows.filter((row) => !ours.has(row.name));
    const taken = new Set();

    // A file written before the group gates were folded in states the weight
    // where this run states the rate, so a row is "the same chance" under
    // either number. After the first apply the two agree and only the folded
    // one ever matches.
    const sameChance = (row, drop) => row.chance === drop.chance || row.rawChance === drop.chance;

    for (const drop of unmatchedOurs) {
      // Same chance and same icon is the same row under a new name. Where the
      // icon moved too — which happens, since the same revision that adds the
      // prefix also repoints some icons — fall back to the chance and one name
      // containing the other, or the pair reads as an unrelated add and remove.
      let index = unmatchedTheirs.findIndex(
        (row, i) => !taken.has(i) && sameChance(row, drop) && row.itemId === drop.itemId,
      );

      if (index === -1) {
        index = unmatchedTheirs.findIndex(
          (row, i) =>
            !taken.has(i) &&
            sameChance(row, drop) &&
            (row.name.includes(drop.name) || drop.name.includes(row.name)),
        );
      }

      if (index === -1) {
        report.removed.push(`${boss.name} / ${drop.name} @ ${drop.chance}%`);
        continue;
      }

      taken.add(index);
      const key = `${drop.name}  ->  ${unmatchedTheirs[index].name}`;
      report.renamed.set(key, (report.renamed.get(key) ?? 0) + 1);
    }

    unmatchedTheirs.forEach((row, i) => {
      if (!taken.has(i)) report.added.push(`${boss.name} / ${row.name} @ ${row.chance}%`);
    });
  }

  const known = new Set(current.map((boss) => boss.id));
  for (const boss of parsed) if (!known.has(boss.id)) report.bosses.gained.push(boss.name);

  // An icon key the source introduces needs a file on disk, or the seed fails
  // on upload. Cheaper to find out here than three commands later.
  for (const boss of parsed) {
    for (const row of boss.drops.ours ?? []) {
      if (row.itemId && !fs.existsSync(path.join(ICONS_DIR, `${row.itemId}.webp`))) {
        report.missingIcons.add(row.itemId);
      }
    }
  }

  return report;
};

const print = (report) => {
  const renamedRows = [...report.renamed.values()].reduce((sum, n) => sum + n, 0);

  console.info('  renamed        : %d rows in %d names', renamedRows, report.renamed.size);
  console.info('  only on source : %d rows', report.added.length);
  console.info('  only in file   : %d rows', report.removed.length);
  console.info('  values changed : %d rows', report.changed.length);
  console.info('  grade changed  : %d rows', report.regraded.length);
  console.info('  icon key moved : %d rows', report.iconMoved.length);
  console.info(
    '  bosses gained  : %d   lost: %d',
    report.bosses.gained.length,
    report.bosses.only.length,
  );

  const sample = (label, list) => {
    if (!list.length) return;
    console.info('\n  %s:', label);
    for (const line of list.slice(0, 8)) console.info('    %s', line);
    if (list.length > 8) console.info('    ... and %d more', list.length - 8);
  };

  sample(
    'renamed',
    [...report.renamed].map(([key, n]) => `${n}x  ${key}`),
  );
  sample('only on source', report.added);
  sample('only in file', report.removed);
  sample('values changed', report.changed);
  sample('grade changed', report.regraded);
  sample('icon key moved', report.iconMoved);

  if (report.slugs.length) {
    console.warn('\n  %d bosses are slugged differently by the source:', report.slugs.length);
    for (const line of report.slugs.slice(0, 8)) console.warn('      %s', line);
    if (report.slugs.length > 8) console.warn('      ... and %d more', report.slugs.length - 8);
    console.warn("  A slug is this catalogue's identity for a record, so these are not");
    console.warn('  adopted by --write. Pass --adopt-slugs as well, and expect the seed to');
    console.warn('  create new records and strand the old ones unless the table is emptied.');
  }

  if (report.missingIcons.size) {
    console.warn(
      '\n  %d icon keys have no .webp in mocks/raid-bosses/images/item-icons:',
      report.missingIcons.size,
    );
    for (const key of [...report.missingIcons].slice(0, 12)) console.warn('    %s', key);
    console.warn('  The seed uploads by path and will fail on these until they are converted.');
  }
};

const write = async (parsed, session, { adoptSlugs = false } = {}) => {
  // `data-wiki.ts` is edited in place: it holds imagery, coordinates,
  // statistics and respawn this page cannot see. Only the two flags and, when
  // asked for, the slug are replaced.
  const bosses = readBosses();
  const byId = new Map(parsed.map((boss) => [boss.id, boss]));
  let touched = 0;

  for (const boss of bosses) {
    const source = byId.get(boss.id);
    if (!source?.drops.ours) continue;
    boss.epic = source.epic;
    boss.subclass = source.subclass;
    // Identity, so never on a routine run: see the warning `print` gives.
    if (adoptSlugs) boss.slug = source.slug;
    touched++;
  }

  fs.writeFileSync(
    BOSSES_FILE,
    stampSource(
      replaceExport(fs.readFileSync(BOSSES_FILE, 'utf8'), 'RAID_BOSSES', bosses),
      session.copy,
    ),
  );
  console.info('  bosses: %d updated -> %s', touched, path.relative(process.cwd(), BOSSES_FILE));

  // Drops are regenerated whole: everything in that file comes from this one
  // page, so there is nothing in it to preserve.
  const drops = {};
  for (const boss of parsed) {
    if (boss.drops.ours) drops[boss.id] = boss.drops.ours.map(toDrop);
  }

  if (!fs.existsSync(DROPS_FILE)) fs.writeFileSync(DROPS_FILE, DROPS_HEADER);
  fs.writeFileSync(
    DROPS_FILE,
    stampSource(
      replaceExport(fs.readFileSync(DROPS_FILE, 'utf8'), 'RAID_BOSS_DROPS', drops),
      session.copy,
    ),
  );
  console.info(
    '  drops : %d bosses -> %s',
    Object.keys(drops).length,
    path.relative(process.cwd(), DROPS_FILE),
  );

  // Both servers' tables name icons; fetch whatever has no file behind it.
  // The other server's keys count too. Its drops are written by `refresh:gamma`
  // rather than here, but they land in the same directory and a missing file
  // there is the same missing file.
  const keys = parsed.flatMap((boss) =>
    [...(boss.drops.ours ?? []), ...(boss.drops.other ?? [])].map((row) => row.itemId),
  );
  reportIcons('icons', await ensureIcons(session, keys, ICONS_DIR));

  execFileSync('pnpm', ['exec', 'biome', 'format', '--write', BOSSES_FILE, DROPS_FILE], {
    cwd: path.join(__dirname, '..', '..'),
    stdio: 'inherit',
  });
};

const main = async () => {
  const argv = process.argv.slice(2);
  const session = createSession({ copy: copyFromArgv(argv) });
  announceCopy(session, { expected: 1 });

  console.info('reading %s', ARTICLE);
  const parsed = parseArticle(await session.getCached(ARTICLE));
  console.info(
    '  %d bosses, %d drop rows for this server\n',
    parsed.length,
    parsed.reduce((sum, boss) => sum + (boss.drops.ours?.length ?? 0), 0),
  );

  if (!parsed.length) throw new Error('the article yielded no bosses; refusing to go further');

  print(compare(readBosses(), readDrops(), parsed));

  if (argv.includes('--write')) {
    console.info('\napplying');
    await write(parsed, session, { adoptSlugs: argv.includes('--adopt-slugs') });
    nextStep('drops', true);
  } else {
    nextStep('drops', false);
  }
};

main().catch((error) => {
  console.error('refresh:drops failed:', error.message);
  process.exit(1);
});
