// Records where the other game server, Gamma, differs from this one.
//
// Not a second catalogue. A boss absent from what this writes is a boss the
// two servers agree about, and this server's record applies to it unchanged.
// Measured when the shape was chosen: 151 of 158 bosses are identical, and the
// seven that are not are exactly the three epics and the four subclass bosses.
//
// Which bosses differ is decided by the shared article, which states a level,
// eight statistics and both servers' drop tables. That article cannot see
// accuracy, evasion, the soul-crystal level, respawn or skills, so `--sweep`
// reads every boss's Gamma page instead of only the flagged ones. The sweep is
// how the blind spot was measured rather than assumed; it is not for routine
// use, because it costs a page per boss against a host that throttles.
//
// A differing boss is recorded in full, because a partial copy cannot answer
// the questions a reader would ask and its incompleteness is invisible until
// someone tries. The values that can differ come from the Gamma page; identity
// and geography come from this server, since it is the same boss standing in
// the same place and the Gamma pages name locations in another language.
//
// Usage:
//   pnpm --filter backend refresh:gamma               report only
//   pnpm --filter backend refresh:gamma:write         apply to data-wiki-gamma.ts
//   pnpm --filter backend refresh:gamma -- --sweep    read every boss's page
//   pnpm --filter backend refresh:gamma -- --cache=2026-09-19

const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { execFileSync } = require('node:child_process');

const { announceCopy, copyFromArgv, createSession, SERVER } = require('./fetch');
const { parseArticle } = require('./parse-article');
const { parseBoss } = require('./parse-boss');
const { parseBossSkills } = require('./parse-skills');
const { effectiveChance, sameDrop, toDrop } = require('./drop-row');
const { replaceExport, stampSource } = require('./serialize');
const { createProgress } = require('./progress');
const { nextStep } = require('./steps');

const ARTICLE = `/${SERVER}/posts/post/385-raid-bosses`;
const OTHER_SERVER = 'lu4-gamma';
const MOCKS = path.join(__dirname, '..', '..', 'mocks', 'raid-bosses');
const BOSSES_FILE = path.join(MOCKS, 'data-wiki.ts');
const DROPS_FILE = path.join(MOCKS, 'drops.ts');
const GAMMA_FILE = path.join(MOCKS, 'data-wiki-gamma.ts');

/** The eight the shared article states for Gamma. */
const ARTICLE_STATS = ['hp', 'mp', 'exp', 'sp', 'pAtk', 'mAtk', 'pDef', 'mDef'];
const ALL_STATS = [...ARTICLE_STATS, 'acc', 'eva'];

const HEADER = `// Where the other game server, Gamma, differs from this one.
//
// Generated by \`pnpm --filter backend refresh:gamma:write\`; do not edit by
// hand. Not a second catalogue: a boss absent from here is a boss the two
// servers agree about, and \`data-wiki.ts\` applies to it unchanged.
//
// The bosses here are recorded in full rather than as the subset one shared
// page happens to state, because a copy that omits the fields a reader asks
// about cannot be used and its gaps are invisible until someone tries. What
// can differ — level, every statistic, the soul-crystal level, respawn, race,
// skills and the drops — is the other server's own. What cannot — which boss
// it is, where it stands, what it looks like, and both coordinate pairs — is
// taken from this server, because it is the same boss in the same place and
// the Gamma pages name locations in another language.
//
// Who belongs here is decided by the shared article, which states a level,
// eight statistics and both drop tables. It cannot see accuracy, evasion, the
// soul-crystal level, respawn or skills, so on 2026-09-20 every boss's Gamma
// page was read once to find out whether that blind spot hid anything. It did
// not: 158 bosses compared on every field both servers state, seven differ,
// and the article had flagged all seven. The other 151 are identical down to
// accuracy and evasion. Re-run \`refresh:gamma -- --sweep\` to check that
// again rather than re-deriving it.

import type { RaidBossDrops, RaidBossInfo } from './types';

export const GAMMA_BOSSES: RaidBossInfo[] = [];

export const GAMMA_DROPS: RaidBossDrops = {};
`;

/** Reads a data file the way `catalog-source.ts` does: as text, in a sandbox. */
const evaluate = (file, exported) =>
  vm.runInNewContext(
    fs
      .readFileSync(file, 'utf8')
      .replace(/^import[^;]+;$/gm, '')
      .replace(/export const (\w+)\s*(?::[^=]+)?=/g, 'const $1 =')
      .concat(`\n;({ ${exported} })`),
    Object.create(null),
    { timeout: 30000 },
  );

/** Every drop row the article states for one server, folded to real rates. */
const rowsByName = (rows) =>
  new Map((rows ?? []).map((row) => [row.name, { ...row, chance: effectiveChance(row) }]));

/**
 * Whether the article alone shows this boss differing.
 *
 * The routine detector. It sees a level, eight statistics and both drop
 * tables — enough for every difference measured so far, and `--sweep` is what
 * established that.
 */
const articleFlags = (boss, ours, ourDrops) => {
  if (!ours || boss.otherLevel === null || !boss.otherStats) return false;
  if (boss.otherLevel !== ours.level) return true;
  if (ARTICLE_STATS.some((key) => boss.otherStats[key] !== ours.stats[key])) return true;

  const theirs = rowsByName(boss.drops.other);
  const mine = new Map((ourDrops ?? []).map((drop) => [drop.name, drop]));
  if (theirs.size !== mine.size) return true;
  for (const [name, row] of theirs) {
    const drop = mine.get(name);
    if (!drop || !sameDrop(drop, row)) return true;
  }

  return false;
};

/** Every field both servers state, and where the two disagree. */
const pageDiffers = (gamma, ours, skills) => {
  const why = [];
  if (gamma.level !== ours.level) why.push(`level ${ours.level} -> ${gamma.level}`);
  if (gamma.race !== ours.race) why.push(`race ${ours.race} -> ${gamma.race}`);
  for (const key of ALL_STATS) {
    if (gamma.stats?.[key] !== ours.stats[key]) why.push(key);
  }
  if ((gamma.saMaxLevel ?? null) !== (ours.saMaxLevel ?? null)) {
    why.push(`SA ${ours.saMaxLevel ?? '-'} -> ${gamma.saMaxLevel ?? '-'}`);
  }
  if (gamma.respawn.raw !== ours.respawn.raw) why.push('respawn');
  if (skills.join(',') !== [...ours.skills].sort().join(',')) why.push('skills');

  return why;
};

/**
 * One boss as Gamma has it.
 *
 * Composed rather than copied: the fields that can differ come from Gamma's
 * page and the drops from the article's Gamma table, and everything that
 * cannot differ is this server's. See the file header for why that is not
 * passing one server's values off as the other's.
 */
const compose = (ours, gamma, skills) => ({
  id: ours.id,
  slug: ours.slug,
  name: ours.name,
  race: gamma.race,
  level: gamma.level,
  epic: ours.epic,
  subclass: ours.subclass,
  locations: ours.locations,
  avatar: ours.avatar,
  mapX: ours.mapX,
  mapY: ours.mapY,
  wikiX: ours.wikiX,
  wikiY: ours.wikiY,
  respawn: gamma.respawn,
  stats: gamma.stats,
  skills,
  ...(gamma.saMaxLevel === null ? {} : { saMaxLevel: gamma.saMaxLevel }),
});

const main = async () => {
  const argv = process.argv.slice(2);
  const sweep = argv.includes('--sweep');
  const session = createSession({ copy: copyFromArgv(argv) });
  announceCopy(session, { expected: sweep ? 158 : 7 });

  const roster = parseArticle(await session.getCached(ARTICLE));
  const { RAID_BOSSES } = evaluate(BOSSES_FILE, 'RAID_BOSSES');
  const { RAID_BOSS_DROPS } = evaluate(DROPS_FILE, 'RAID_BOSS_DROPS');
  const ours = new Map(RAID_BOSSES.map((boss) => [boss.id, boss]));

  const onlyHere = RAID_BOSSES.filter((boss) => !roster.some((row) => row.id === boss.id));
  const onlyThere = roster.filter((row) => !ours.has(row.id));

  const flagged = roster.filter((boss) =>
    articleFlags(boss, ours.get(boss.id), RAID_BOSS_DROPS[boss.id]),
  );
  const toRead = sweep ? roster : flagged;

  console.info(
    '%s; reading %d of %d bosses from %s\n',
    sweep ? 'sweep: every boss' : `the article flags ${flagged.length}`,
    toRead.length,
    roster.length,
    OTHER_SERVER,
  );

  const differing = [];
  const hidden = [];
  const progress = createProgress(toRead.length, 'Gamma pages read');

  for (const boss of toRead) {
    const mine = ours.get(boss.id);
    if (!mine) {
      progress.tick(boss.name);
      continue;
    }

    const html = await session.getCached(`/${OTHER_SERVER}/npc/${boss.slug}`);
    const gamma = parseBoss(html);
    const skills = parseBossSkills(html)
      .map((skill) => skill.key)
      .sort();
    const why = pageDiffers(gamma, mine, skills);

    if (why.length) {
      differing.push({ boss, mine, gamma, skills, why });
      // A boss the article did not flag, differing only in what it cannot see,
      // is the finding this sweep exists for.
      if (!flagged.includes(boss)) hidden.push(`${mine.name}: ${why.join(', ')}`);
    }
    progress.tick(boss.name);
  }

  progress.finish();

  console.info('  differ  %d of %d read', differing.length, toRead.length);
  for (const row of differing) {
    console.info('      %s %s', row.mine.name.padEnd(24), row.why.slice(0, 6).join(', '));
  }

  if (sweep) {
    console.info(
      '\n  the article missed %d of them — it states a level, eight statistics and the drops',
      hidden.length,
    );
    for (const line of hidden) console.info('      %s', line);
  }

  if (onlyHere.length || onlyThere.length) {
    console.warn('\n  the two rosters disagree, which nothing here knows how to read:');
    for (const boss of onlyHere) console.warn('      only on this server: %s', boss.name);
    for (const boss of onlyThere) console.warn('      only on %s: %s', OTHER_SERVER, boss.name);
  }

  if (!argv.includes('--write')) {
    nextStep('gamma', false);

    return;
  }

  // Two servers with nothing between them is what a broken comparison looks
  // like, not news. Writing it would erase what is known.
  if (!differing.length) {
    throw new Error(
      'the comparison found no differing bosses at all. That is what a broken ' +
        'comparison looks like rather than two identical servers; nothing written.',
    );
  }

  if (!sweep && flagged.length !== differing.length) {
    throw new Error(
      `the article flagged ${flagged.length} bosses and their pages show ${differing.length}. ` +
        'Run with --sweep to see what the article cannot.',
    );
  }

  console.info('\napplying');
  if (!fs.existsSync(GAMMA_FILE)) fs.writeFileSync(GAMMA_FILE, HEADER);

  const bosses = differing.map((row) => compose(row.mine, row.gamma, row.skills));
  const drops = {};
  for (const row of differing) {
    drops[row.boss.id] = (row.boss.drops.other ?? []).map(toDrop);
  }

  let source = fs.readFileSync(GAMMA_FILE, 'utf8');
  source = replaceExport(source, 'GAMMA_BOSSES', bosses);
  source = replaceExport(source, 'GAMMA_DROPS', drops);
  fs.writeFileSync(GAMMA_FILE, stampSource(source, session.copy));
  execFileSync('pnpm', ['exec', 'biome', 'format', '--write', GAMMA_FILE], {
    cwd: path.join(__dirname, '..', '..'),
    stdio: 'inherit',
  });

  console.info(
    '  %d bosses, %d drop rows -> %s',
    bosses.length,
    Object.values(drops).reduce((total, rows) => total + rows.length, 0),
    path.relative(process.cwd(), GAMMA_FILE),
  );
  nextStep('gamma', true);
};

main().catch((error) => {
  console.error('refresh:gamma failed:', error.message);
  process.exit(1);
});
