// Builds the skill vocabulary out of the boss pages the profile pass cached.
//
// Costs no requests for the skills themselves: every modifier is in the
// dropdown beside the skill on each boss's own page. See `parse-skills.js` for
// why that is, and for why what is kept is decided by what a skill says rather
// than by a list of blessed group numbers.
//
// It does fetch the icons, and only the ones with no file yet.
//
// Requires the boss pages to be cached, which means running the profile refresh
// first. Reading them again here would be 158 requests for data already on
// disk.
//
// Usage:
//   pnpm --filter backend refresh:skills             report only
//   pnpm --filter backend refresh:skills:write        write skills.ts

const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const { announceCopy, copyFromArgv, createSession, SERVER } = require('./fetch');
const { parseArticle } = require('./parse-article');
const { nextStep } = require('./steps');
const { parseBossSkills } = require('./parse-skills');
const { ensureIcons, reportIcons } = require('./icons');
const { replaceExport, stampSource } = require('./serialize');

const ARTICLE = `/${SERVER}/posts/post/385-raid-bosses`;
const MOCKS = path.join(__dirname, '..', '..', 'mocks', 'raid-bosses');
const SKILLS_FILE = path.join(MOCKS, 'skills.ts');
const ICONS_DIR = path.join(MOCKS, 'images', 'skill-icons');

const HEADER = `// The skills the raid bosses carry, and what each one shifts about a fight.
//
// Generated by \`pnpm --filter backend refresh:skills -- --write\`; do not edit
// by hand. Built from the boss pages rather than from the skills' own: the
// dropdown beside a skill on a boss's page states the description of the level
// that boss has, so the whole vocabulary comes out of pages already fetched.
//
// A boss names these by key in its \`skills\` field. Only skills that say
// something about defending against a boss are here — a dropdown yielding
// neither a numbered line nor a named affinity is not recorded, which leaves
// out the lore, the shared raid mechanics, and the stat-scale descriptors whose
// carriers all sit at a neutral level.

import type { SkillInfo } from './types';

export const SKILLS: SkillInfo[] = [];
`;

const main = async () => {
  const argv = process.argv.slice(2);
  const session = createSession({ copy: copyFromArgv(argv) });
  announceCopy(session);

  const roster = parseArticle(await session.getCached(ARTICLE));
  const skills = new Map();
  const carriers = new Map();
  const conflicts = [];
  let missingPages = 0;

  for (const boss of roster) {
    const page = session.cachePath(`/${SERVER}/npc/${boss.slug}`);
    if (!fs.existsSync(page)) {
      missingPages++;
      continue;
    }

    const carried = parseBossSkills(fs.readFileSync(page, 'utf8'));
    for (const skill of carried) {
      if (!skills.has(skill.key)) skills.set(skill.key, skill);
      carriers.set(skill.key, (carriers.get(skill.key) ?? 0) + 1);
    }

    // Two of a boss's skills may shift the same subject. In one unit they add
    // up and there is nothing to say. In different units they cannot, and a
    // pair pointing opposite ways is worth a person's attention: the catalogue
    // keeps both, and the reading client ranks the personal one over the racial.
    const bySubject = new Map();
    for (const skill of carried) {
      for (const modifier of skill.modifiers) {
        const subject = `${modifier.kind}:${modifier.subject}`;
        bySubject.set(subject, [...(bySubject.get(subject) ?? []), { ...modifier, skill }]);
      }
    }

    for (const [subject, found] of bySubject) {
      if (found.length < 2) continue;
      const units = new Set(found.map((modifier) => modifier.unit));
      const directions = new Set(found.map((modifier) => Math.sign(modifier.value)));
      if (units.size < 2 || directions.size < 2) continue;

      conflicts.push(
        `${boss.name} / ${subject}: ` +
          found.map((m) => `${m.skill.key} ${m.skill.origin} ${m.value}${m.unit}`).join('  vs  '),
      );
    }
  }

  if (missingPages) {
    throw new Error(
      `${missingPages} of ${roster.length} boss pages are not cached. ` +
        'Run `refresh:profile` until every boss has been read; this command adds no requests of its own.',
    );
  }

  const byOrigin = new Map();
  for (const skill of skills.values()) {
    byOrigin.set(skill.origin, (byOrigin.get(skill.origin) ?? 0) + 1);
  }

  console.info('  skills            %d', skills.size);
  console.info(
    '  by origin         %s',
    [...byOrigin].map(([origin, n]) => `${origin} ${n}`).join(', '),
  );
  console.info(
    '  boss-to-skill     %d',
    [...carriers.values()].reduce((sum, n) => sum + n, 0),
  );
  console.info(
    '  modifiers         %d',
    [...skills.values()].reduce((sum, skill) => sum + skill.modifiers.length, 0),
  );

  if (conflicts.length) {
    console.warn('\n  %d bosses are told opposite things about one subject:', conflicts.length);
    for (const line of conflicts) console.warn('      %s', line);
    console.warn('  Both are kept. The reading client ranks a personal skill over a racial one.');
  }

  if (!argv.includes('--write')) {
    nextStep('skills', false);
    return;
  }

  console.info('\napplying');
  reportIcons(
    'icons',
    await ensureIcons(
      session,
      [...skills.values()].map((skill) => skill.icon),
      ICONS_DIR,
    ),
  );

  if (!fs.existsSync(SKILLS_FILE)) fs.writeFileSync(SKILLS_FILE, HEADER);

  const ordered = [...skills.values()]
    .sort((a, b) => a.group.localeCompare(b.group) || a.level - b.level)
    .map((skill) => ({
      key: skill.key,
      group: skill.group,
      level: skill.level,
      name: skill.name,
      origin: skill.origin,
      icon: skill.icon,
      modifiers: skill.modifiers,
    }));

  fs.writeFileSync(
    SKILLS_FILE,
    stampSource(
      replaceExport(fs.readFileSync(SKILLS_FILE, 'utf8'), 'SKILLS', ordered),
      session.copy,
    ),
  );
  execFileSync('pnpm', ['exec', 'biome', 'format', '--write', SKILLS_FILE], {
    cwd: path.join(__dirname, '..', '..'),
    stdio: 'inherit',
  });
  console.info(
    '  %d skills written -> %s',
    ordered.length,
    path.relative(process.cwd(), SKILLS_FILE),
  );
  nextStep('skills', true);
};

main().catch((error) => {
  console.error('refresh:skills failed:', error.message);
  process.exit(1);
});
