/**
 * Reads the scraped raid-boss reference at
 * `apps/backend/mocks/raid-bosses/data.ts` and turns it into the shapes the
 * catalogue stores. Pure: no Strapi, no database, no filesystem beyond reading
 * that one file and naming the images beside it — so the corrections below can
 * be tested without booting anything.
 *
 * The file is a 795 KB TypeScript literal that nothing imports at runtime; it
 * is input to the seed and only that. It is read as text, its `import type`
 * line and type annotations stripped, and evaluated, rather than `import`ed
 * normally. Fragile in principle, but the file is generated by
 * `mocks/raid-bosses/fetch.js` and its shape changes only when that script does.
 *
 * Three defects in the source are corrected on the way through, each one
 * verified against the data rather than assumed:
 *
 *   * `itemId` is not an item identity. It is the source's icon field, and
 *     `itemId === basename(icon)` holds for all 2791 drop rows. 737 distinct
 *     item names share 359 icons, so keying items on it would collapse the
 *     catalogue to less than half. Items are keyed by name; `itemId` survives
 *     only as the key that finds the uploaded icon.
 *
 *   * Four bosses carry the location slug `x`, under which the scraper
 *     collapsed two different places it could not slugify — both named in
 *     Russian. They are split back apart by name.
 *
 *   * `_iNN` on an icon name looks like noise and is not: stripping it would
 *     merge the four enchant-armour scrolls into one, the four enchant-weapon
 *     scrolls into one, and the Physical and Magical Rings of Queen Ant into
 *     each other. It is left alone, which is why nothing here touches it.
 */

import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const SOURCE_RELATIVE = path.join('apps', 'backend', 'mocks', 'raid-bosses', 'data.ts');

/**
 * The monorepo root, found by walking up for a landmark rather than by counting
 * `..` segments.
 *
 * This module runs from two different depths — `src/helpers` under vitest,
 * which transpiles in place, and `dist/src/helpers` under the seed script,
 * which runs the compiled output — so a fixed relative path is correct in one
 * and wrong in the other, and the failure is an ENOENT that names nothing.
 *
 * Anchoring on the root also keeps the hand-edited grades file pointing at the
 * source tree from both, which matters: the export writes it, and a copy inside
 * `dist/` would be overwritten by the next compile and never reach git.
 */
const findRepoRoot = () => {
  let dir = __dirname;

  for (;;) {
    if (fs.existsSync(path.join(dir, SOURCE_RELATIVE))) return dir;

    const parent = path.dirname(dir);
    if (parent === dir) {
      throw new Error(`Could not find ${SOURCE_RELATIVE} above ${__dirname}`);
    }
    dir = parent;
  }
};

const REPO_ROOT = findRepoRoot();
const SOURCE_FILE = path.join(REPO_ROOT, SOURCE_RELATIVE);

/** Where the images sit, relative to the source file. */
const IMAGES_DIR = path.join(path.dirname(SOURCE_FILE), 'images');

/**
 * The two places the scraper flattened into the slug `x`, keyed by the Russian
 * name it did produce. Translations chosen for this change — the source
 * contains no English name for either.
 */
const COLLAPSED_LOCATIONS: Record<string, { slug: string; name: string }> = {
  'Восточная Пограничная Застава': {
    slug: 'eastern-border-outpost',
    name: 'Eastern Border Outpost',
  },
  'Место обитания Рачиков': { slug: 'lachik-habitat', name: 'Lachik Habitat' },
};

/** Weakest first, so `order` sorts the way the game does. */
export const GRADES = [
  { code: 'ng', label: 'NG', order: 0 },
  { code: 'd', label: 'D', order: 1 },
  { code: 'c', label: 'C', order: 2 },
  { code: 'b', label: 'B', order: 3 },
  { code: 'a', label: 'A', order: 4 },
  { code: 's', label: 'S', order: 5 },
];

export const DEFAULT_GRADE_CODE = 'ng';

/**
 * A boss's grade, from its level.
 *
 * Grade is this catalogue's own idea — the scrape has no such field — and 153
 * bosses is too many to set by hand for a value that level predicts. The bands
 * were chosen by the operator; the seed applies them as the default, and
 * `catalog-grades.json` still wins wherever somebody disagreed.
 *
 * `S` is deliberately unreachable: the three epics sit at level 72 and take `A`
 * like everything else above 61. It stays in the vocabulary for later.
 */
export const gradeForLevel = (level: number): string => {
  if (level < 40) return 'd';
  if (level <= 49) return 'c';
  if (level <= 61) return 'b';

  return 'a';
};

/**
 * The grade an item states in its own name — `Scroll: Enchant Armor (D-Grade)`.
 *
 * Sixteen items say so, and the name outranks the grade of the bosses that drop
 * them: an item naming its own grade is evidence about itself, where the drop
 * table is evidence about who carries it. In practice the two never disagree —
 * checked across all sixteen, and where the bosses span bands the name picks one
 * of the bands they span — so this decides nothing today that the boss rule
 * decided differently. What it does decide is the eight the boss rule could not:
 * the C- and D-grade scrolls, dropped across two bands each.
 */
export const gradeFromName = (name: string): string | null => {
  const match = name.match(/\((NG|S|A|B|C|D)-Grade\)/i);
  if (!match?.[1]) return null;

  const code = match[1].toLowerCase();

  return GRADES.some((grade) => grade.code === code) ? code : null;
};

/**
 * The weapon vocabulary, as records rather than an enumeration on each boss.
 *
 * Six terms against 120 usages: `dagger` alone appears 33 times. A label kept
 * beside each usage would be the same string stored 33 times and 33 rows to
 * change, and a localised one would be 33 copies per language of a word that
 * needs translating once.
 */
export const WEAPON_TYPES = [
  { code: 'blunt', label: 'Blunt' },
  { code: 'bow', label: 'Bow' },
  { code: 'dagger', label: 'Dagger' },
  { code: 'fist', label: 'Fist' },
  { code: 'spear', label: 'Spear' },
  { code: 'sword', label: 'Sword' },
];

/**
 * Grades are this catalogue's own idea — the scrape has no such field — and are
 * set by hand after seeding. They cannot live in `data.ts`, which is generated
 * by `mocks/raid-bosses/fetch.js` and says so on its first line, so they get
 * their own file: a map of slug to grade code, written by the export script and
 * read here.
 *
 * Missing file, missing entry or unknown slug all fall back to `NG`. Being
 * incomplete is the normal state — a grade is only listed once someone has set
 * it.
 */
export interface CatalogGrades {
  bosses: Record<string, string>;
  items: Record<string, string>;
}

export const GRADES_FILE = path.join(
  REPO_ROOT,
  'apps',
  'backend',
  'src',
  'helpers',
  'catalog-grades.json',
);

export const readCatalogGrades = (): CatalogGrades => {
  if (!fs.existsSync(GRADES_FILE)) return { bosses: {}, items: {} };

  const parsed = JSON.parse(fs.readFileSync(GRADES_FILE, 'utf8')) as Partial<CatalogGrades>;

  return { bosses: parsed.bosses ?? {}, items: parsed.items ?? {} };
};

interface RawDrop {
  itemId: string;
  name: string;
  chance: number;
  minCount: number;
  maxCount: number;
  icon: string | null;
}

interface RawBoss {
  id: string;
  slug: string;
  name: string;
  race: string;
  level: number;
  epic: boolean;
  locations: { name: string; slug: string }[];
  avatar: { full: string; mini: string };
  mapX: number;
  mapY: number;
  worldX: number;
  worldY: number;
  respawn: { fixed: boolean; baseHours: number | null; varianceHours: number | null };
  stats: Record<string, number>;
  weaponResistances: string[];
  weaponVulnerabilities: string[];
  elementModifiers?: Record<string, number>;
  saMaxLevel?: number;
  statModifiers?: Record<string, number>;
  drops: RawDrop[];
}

interface RawPlan {
  name: string;
  mapX: number;
  mapY: number;
  width: number;
  height: number;
  image: string;
}

export interface CatalogLocation {
  slug: string;
  name: string;
  dungeon: { imagePath: string; mapX: number; mapY: number; width: number; height: number } | null;
}

export interface CatalogAvatar {
  slug: string;
  fullPath: string;
  miniPath: string;
}

export interface CatalogItem {
  slug: string;
  name: string;
  /** The source's `itemId`: names the icon, never the item. */
  iconKey: string | null;
  /**
   * What the item calls itself, else the grade of the bosses that drop it when
   * they agree. When neither settles it — six items, `Proof of Loyalty` above
   * all, which falls from 150 bosses across every band — it stays at the
   * default rather than guessing, and the name is listed in `ambiguousItems`.
   */
  grade: string;
}

export interface CatalogBoss {
  slug: string;
  gameId: string;
  name: string;
  race: string;
  level: number;
  epic: boolean;
  /** Derived from `level`; see `gradeForLevel`. */
  grade: string;
  saMaxLevel: number | null;
  mapX: number;
  mapY: number;
  worldX: number;
  worldY: number;
  respawn: {
    kind: 'interval' | 'scheduled';
    baseMinutes: number | null;
    varianceMinutes: number | null;
  };
  stats: Record<string, number>;
  resistances: string[];
  vulnerabilities: string[];
  elementModifiers: { element: string; value: number }[];
  statModifiers: { stat: string; value: number }[];
  locationSlug: string;
  avatarSlug: string;
}

export interface CatalogDrop {
  bossSlug: string;
  itemName: string;
  chance: number;
  minCount: number;
  maxCount: number;
}

export interface CatalogSource {
  locations: CatalogLocation[];
  avatars: CatalogAvatar[];
  items: CatalogItem[];
  bosses: CatalogBoss[];
  drops: CatalogDrop[];
  /** icon key -> absolute path, for the upload step. */
  icons: Map<string, string>;
  worldMapPath: string;
  /** Items whose source bosses disagree on grade, so it was not derived. */
  ambiguousItems: string[];
}

/** Turns an item name into a URL-safe slug. Checked: 737 names, 737 slugs. */
export const slugify = (value: string) =>
  value
    .toLowerCase()
    // Decompose, then drop the combining marks NFKD split off, so an accented
    // letter becomes its plain counterpart instead of vanishing at the
    // alphanumeric filter below.
    .normalize('NFKD')
    .replace(/\p{Mn}/gu, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

const readRaw = (): { bosses: RawBoss[]; plans: Record<string, RawPlan>; worldMap: string } => {
  const text = fs.readFileSync(SOURCE_FILE, 'utf8');
  const script = text
    .replace(/^import[^;]+;$/gm, '')
    .replace(/export const (\w+)\s*(?::[^=]+)?=/g, 'const $1 =')
    .concat('\n;({ RAID_BOSSES, DUNGEON_PLANS, WORLD_MAP_IMAGE })');

  const result = vm.runInNewContext(script, Object.create(null), {
    filename: SOURCE_FILE,
    timeout: 30_000,
  }) as { RAID_BOSSES: RawBoss[]; DUNGEON_PLANS: Record<string, RawPlan>; WORLD_MAP_IMAGE: string };

  return {
    bosses: result.RAID_BOSSES,
    plans: result.DUNGEON_PLANS,
    worldMap: result.WORLD_MAP_IMAGE,
  };
};

/**
 * The location a boss belongs to, with the scraper's `x` collapse undone.
 * Every boss has exactly one — checked across all 153, min 1 and max 1 — which
 * is why the relation is many-to-one and not the many-to-many the array shape
 * would suggest.
 */
const locationOf = (boss: RawBoss) => {
  const raw = boss.locations[0];
  if (!raw) throw new Error(`Boss ${boss.slug} has no location`);

  const repaired = COLLAPSED_LOCATIONS[raw.name];

  return repaired ?? { slug: raw.slug, name: raw.name };
};

const toMinutes = (hours: number | null) => (hours === null ? null : Math.round(hours * 60));

export const readCatalogSource = (): CatalogSource => {
  const { bosses: raw, plans, worldMap } = readRaw();

  const locations = new Map<string, CatalogLocation>();
  const avatars = new Map<string, CatalogAvatar>();
  const items = new Map<string, CatalogItem>();
  const icons = new Map<string, string>();
  const bosses: CatalogBoss[] = [];
  const drops: CatalogDrop[] = [];
  const gradesByItem = new Map<string, Set<string>>();

  for (const boss of raw) {
    const location = locationOf(boss);
    if (!locations.has(location.slug)) {
      locations.set(location.slug, { slug: location.slug, name: location.name, dungeon: null });
    }

    const avatarSlug = path.basename(boss.avatar.full, '.webp');
    if (!avatars.has(avatarSlug)) {
      avatars.set(avatarSlug, {
        slug: avatarSlug,
        fullPath: path.join(path.dirname(SOURCE_FILE), boss.avatar.full),
        miniPath: path.join(path.dirname(SOURCE_FILE), boss.avatar.mini),
      });
    }

    bosses.push({
      slug: boss.slug,
      gameId: boss.id,
      name: boss.name,
      race: boss.race.toLowerCase(),
      level: boss.level,
      epic: boss.epic,
      grade: gradeForLevel(boss.level),
      saMaxLevel: boss.saMaxLevel ?? null,
      mapX: boss.mapX,
      mapY: boss.mapY,
      worldX: boss.worldX,
      worldY: boss.worldY,
      respawn: boss.respawn.fixed
        ? // The source records these three epics as the literal string "Fixed"
          // and names no day. The shape is here; the entries are authored later.
          { kind: 'scheduled', baseMinutes: null, varianceMinutes: null }
        : {
            kind: 'interval',
            baseMinutes: toMinutes(boss.respawn.baseHours),
            varianceMinutes: toMinutes(boss.respawn.varianceHours),
          },
      stats: boss.stats,
      resistances: boss.weaponResistances.map((weapon) => weapon.toLowerCase()),
      vulnerabilities: boss.weaponVulnerabilities.map((weapon) => weapon.toLowerCase()),
      elementModifiers: Object.entries(boss.elementModifiers ?? {}).map(([element, value]) => ({
        element,
        value,
      })),
      statModifiers: Object.entries(boss.statModifiers ?? {}).map(([stat, value]) => ({
        stat,
        value,
      })),
      locationSlug: location.slug,
      avatarSlug,
    });

    for (const drop of boss.drops) {
      if (!items.has(drop.name)) {
        items.set(drop.name, {
          slug: slugify(drop.name),
          name: drop.name,
          iconKey: drop.itemId || null,
          // Filled in below, once every boss that drops it is known.
          grade: DEFAULT_GRADE_CODE,
        });
      }

      const seen = gradesByItem.get(drop.name) ?? new Set<string>();
      seen.add(gradeForLevel(boss.level));
      gradesByItem.set(drop.name, seen);

      if (drop.itemId && drop.icon && !icons.has(drop.itemId)) {
        icons.set(drop.itemId, path.join(path.dirname(SOURCE_FILE), drop.icon));
      }

      drops.push({
        bossSlug: boss.slug,
        itemName: drop.name,
        chance: drop.chance,
        minCount: drop.minCount,
        maxCount: drop.maxCount,
      });
    }
  }

  // Dungeon plans are keyed by location slug, and every key is a slug some boss
  // uses — checked, none is orphaned.
  for (const [slug, plan] of Object.entries(plans)) {
    const location = locations.get(slug);
    if (!location) continue;

    location.dungeon = {
      imagePath: path.join(path.dirname(SOURCE_FILE), plan.image),
      mapX: plan.mapX,
      mapY: plan.mapY,
      width: plan.width,
      height: plan.height,
    };
  }

  // An item's grade, in order of authority: what it calls itself, then the
  // bosses that drop it when they agree. 731 of the 737 land on one; the last
  // six span bands and say nothing about themselves, so they keep the default
  // rather than being guessed at.
  const ambiguousItems: string[] = [];
  for (const item of items.values()) {
    const named = gradeFromName(item.name);
    if (named) {
      item.grade = named;
      continue;
    }

    const seen = gradesByItem.get(item.name);
    if (!seen) continue;

    if (seen.size === 1) {
      const [only] = [...seen];
      item.grade = only as string;
    } else {
      ambiguousItems.push(item.name);
    }
  }

  return {
    ambiguousItems: ambiguousItems.sort(),
    locations: [...locations.values()],
    avatars: [...avatars.values()],
    items: [...items.values()],
    bosses,
    drops,
    icons,
    worldMapPath: path.join(path.dirname(SOURCE_FILE), worldMap),
  };
};

export const IMAGES_ROOT = IMAGES_DIR;
